apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chosen-raccoon-python 
  janus-idp.io/tekton: chosen-raccoon-python
  backstage.io/kubernetes-id: chosen-raccoon-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: chosen-raccoon-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  